version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    volumes:
      - ../src:/var/www/html
    env_file:
      - app.env

  proxy:
    build:
      context: .
      dockerfile: ./proxy.Dockerfile
    ports: 
      - 80:80 

  mysql:
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ../vols/mysql:/var/lib/mysql
  
  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8001:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
